# Docker Compose for Linier Channel - Using Local MySQL & Redis

services:
  # Linier Channel Application
  app:
    build: .
    container_name: linier-channel-app
    ports:
      - "8080:8080"
    environment:
      # Server Configuration
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      
      # Database Configuration
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Nd45mulh0!
      DB_NAME: linier_channel
      DB_CHARSET: utf8mb4
      
      # Redis Configuration
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      
      # Storage Configuration
      UPLOAD_PATH: /uploads
      TRANCODED_PATH: /transcoded-videos
      ARCHIVE_PATH: /archive
      MAX_FILE_SIZE: 1073741824
      ALLOWED_FORMATS: mp4,avi,mov,mkv
      
      # FFmpeg Configuration
      FFMPEG_PATH: /usr/bin/ffmpeg
      FFPROBE_PATH: /usr/bin/ffprobe
      
      # Transcoding Configuration
      TRANSCODE_WORKERS: 3
      HLS_WINDOW: 15
      SEGMENT_TIME: 4
      
      # Logging Configuration
      LOG_LEVEL: info
      LOG_FORMAT: json
      LOG_PATH: /var/log/linier-channel/app.log
      
      # Kubernetes Configuration
      POD_NAME: ""
      NAMESPACE: default
    volumes:
      # Mount local directories to container (using paths from config.local.env)
      - /Users/herihandoko/Documents/Transcode/input:/uploads
      - /Users/herihandoko/Documents/Transcode/output:/transcoded-videos
      - /Users/herihandoko/Documents/Transcode/archive:/archive
      - /Users/herihandoko/Documents/Transcode/log:/var/log/linier-channel
    extra_hosts:
      # Allow container to access local services
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Nginx for file serving (optional)
  nginx:
    image: nginx:alpine
    container_name: linier-channel-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /Users/herihandoko/Documents/Transcode/output:/usr/share/nginx/html/transcoded:ro
    depends_on:
      - app
    restart: unless-stopped

networks:
  default:
    driver: bridge
