# Docker Compose for Linier Channel

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: linier-channel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: linier_channel
      MYSQL_USER: linier_user
      MYSQL_PASSWORD: linier_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - linier-channel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: linier-channel-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - linier-channel-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5

  # Linier Channel Application
  app:
    build: .
    container_name: linier-channel-app
    ports:
      - "8080:8080"
    environment:
      # Server Configuration
      SERVER_PORT: 8080
      SERVER_HOST: 0.0.0.0
      
      # Database Configuration
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: linier_channel
      DB_CHARSET: utf8mb4
      
      # Redis Configuration
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      
      # Storage Configuration
      UPLOAD_PATH: /uploads
      TRANCODED_PATH: /transcoded-videos
      MAX_FILE_SIZE: 1073741824
      ALLOWED_FORMATS: mp4,avi,mov,mkv
      
      # FFmpeg Configuration
      FFMPEG_PATH: /usr/bin/ffmpeg
      FFPROBE_PATH: /usr/bin/ffprobe
      
      # Transcoding Configuration
      TRANSCODE_WORKERS: 3
      HLS_WINDOW: 15
      SEGMENT_TIME: 4
      
      # Logging Configuration
      LOG_LEVEL: info
      LOG_FORMAT: json
    volumes:
      - uploads_data:/uploads
      - transcoded_data:/transcoded-videos
    networks:
      - linier-channel-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      timeout: 5s
      retries: 3
      start_period: 30s

  # Nginx for file serving (optional)
  nginx:
    image: nginx:alpine
    container_name: linier-channel-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - transcoded_data:/usr/share/nginx/html/transcoded:ro
    networks:
      - linier-channel-network
    depends_on:
      - app

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  uploads_data:
    driver: local
  transcoded_data:
    driver: local

networks:
  linier-channel-network:
    driver: bridge
