apiVersion: apps/v1
kind: Deployment
metadata:
  name: linier-channel
  namespace: linier-channel
  labels:
    app: linier-channel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: linier-channel
  template:
    metadata:
      labels:
        app: linier-channel
    spec:
      containers:
      - name: linier-channel
        image: linier-channel:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: linier-channel-secret
              key: DB_PASSWORD
        - name: DB_NAME
          value: "linier_channel"
        - name: DB_CHARSET
          value: "utf8mb4"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: linier-channel-secret
              key: REDIS_PASSWORD
        - name: REDIS_DB
          value: "0"
        envFrom:
        - configMapRef:
            name: linier-channel-config
        volumeMounts:
        - name: storage
          mountPath: /uploads
        - name: storage
          mountPath: /transcoded-videos
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: linier-channel-storage
      imagePullSecrets:
      - name: regcred  # Adjust based on your registry
