apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linier-channel-storage
  namespace: linier-channel
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-client  # Adjust based on your storage class
